services:
  mysql:
    image: mysql:8.0
    container_name: taller_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taller_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
