services:
  postgres:
    image: postgres:16
    container_name: taller_db
    environment:
      POSTGRES_DB: taller
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Argentina/Buenos_Aires
      PGTZ: America/Argentina/Buenos_Aires
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: