spring.application.name=netadmin
# URL de conexión: jdbc:postgresql://[host]:[puerto]/[nombre_db]
spring.datasource.url=jdbc:postgresql://localhost:5432/netadmin_db

# Credenciales
spring.datasource.username=postgres
spring.datasource.password=1234

# Driver de la base de datos
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (JPA)
# 'update' crea o modifica las tablas automáticamente según tus entidades
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola (útil para desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect