spring.application.name=netadmin
# URL de conexión: jdbc:postgresql://[host]:[puerto]/[nombre_db]
spring.datasource.url=jdbc:postgresql://localhost:5432/netadmin_db

# Credenciales
spring.datasource.username=postgres
spring.datasource.password=postgres

# Driver de la base de datos
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (JPA)
# 'update' crea o modifica las tablas automáticamente según tus entidades
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Columnas en BD: snake_case a partir de atributos camelCase en las entidades
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy